/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.EntradaVotos;

/**
 *
 * @author Oscar
 */
public class Votar extends javax.swing.JFrame {

    EntradaVotos entradaVotos = new EntradaVotos();
    
    /**
     * Creates new form Votar
     */
    public Votar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        btnCandidato1 = new javax.swing.JButton();
        btnCandidato2 = new javax.swing.JButton();
        btnCandidato3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaVer = new javax.swing.JTextArea();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCandidato1.setText("Candidato 1");
        btnCandidato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidato1ActionPerformed(evt);
            }
        });

        btnCandidato2.setText("Candidato 2");
        btnCandidato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidato2ActionPerformed(evt);
            }
        });

        btnCandidato3.setText("Candidato 3");
        btnCandidato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidato3ActionPerformed(evt);
            }
        });

        txaVer.setColumns(20);
        txaVer.setRows(5);
        jScrollPane1.setViewportView(txaVer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnCandidato1)
                .addGap(47, 47, 47)
                .addComponent(btnCandidato2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCandidato3)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCandidato1)
                    .addComponent(btnCandidato2)
                    .addComponent(btnCandidato3))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCandidato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidato1ActionPerformed
        String c = "Candidato1";
        entradaVotos.ManejarEvento(c);
        txaVer.setText(entradaVotos.verVotos());   
    }//GEN-LAST:event_btnCandidato1ActionPerformed

    private void btnCandidato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidato2ActionPerformed
        String c = "Candidato2";
        entradaVotos.ManejarEvento(c);
        txaVer.setText(entradaVotos.verVotos());       
    }//GEN-LAST:event_btnCandidato2ActionPerformed

    private void btnCandidato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidato3ActionPerformed
        String c = "Candidato3";
        entradaVotos.ManejarEvento(c);
        txaVer.setText(entradaVotos.verVotos());   
    }//GEN-LAST:event_btnCandidato3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Votar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Votar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Votar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Votar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Votar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCandidato1;
    private javax.swing.JButton btnCandidato2;
    private javax.swing.JButton btnCandidato3;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaVer;
    // End of variables declaration//GEN-END:variables
}
