/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtrlAdministradores;
import Modelo.Observador;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar
 */
public class MenuPrincipal extends javax.swing.JFrame implements Observador {

    private CtrlAdministradores ctrlAdministradores;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {

        initComponents();
        ctrlAdministradores = new CtrlAdministradores();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnComputadora1 = new javax.swing.JButton();
        btnXbox1 = new javax.swing.JButton();
        btnComputadora2 = new javax.swing.JButton();
        btnComputadora3 = new javax.swing.JButton();
        btnXbox2 = new javax.swing.JButton();
        btnComputadora4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTiempoCompu1 = new javax.swing.JLabel();
        lblTiempoCompu2 = new javax.swing.JLabel();
        lblTiempoXbox1 = new javax.swing.JLabel();
        lblTiempoCompu3 = new javax.swing.JLabel();
        lblTiempoCompu4 = new javax.swing.JLabel();
        lblTiempoXbox2 = new javax.swing.JLabel();
        lblPrecioCompu1 = new javax.swing.JLabel();
        lblPrecioCompu2 = new javax.swing.JLabel();
        lblPrecioXbox1 = new javax.swing.JLabel();
        lblPrecioCompu3 = new javax.swing.JLabel();
        lblPrecioCompu4 = new javax.swing.JLabel();
        lblPrecioXbox2 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnComputadora1.setText("PC 1");
        btnComputadora1.setAutoscrolls(true);
        btnComputadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputadora1ActionPerformed(evt);
            }
        });

        btnXbox1.setText("Xbox1");
        btnXbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXbox1ActionPerformed(evt);
            }
        });

        btnComputadora2.setText("PC 2");
        btnComputadora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputadora2ActionPerformed(evt);
            }
        });

        btnComputadora3.setText("PC 3");
        btnComputadora3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputadora3ActionPerformed(evt);
            }
        });

        btnXbox2.setText("Xbox2");
        btnXbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXbox2ActionPerformed(evt);
            }
        });

        btnComputadora4.setText("PC 4");
        btnComputadora4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputadora4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Hora:");

        jLabel2.setText("Precio: ");

        Hora.setText("Hora: ");

        jLabel4.setText("Precio: ");

        jLabel6.setText("Hora: ");

        jLabel7.setText("Precio: ");

        jLabel8.setText("Hora: ");

        jLabel9.setText("Precio: ");

        jLabel10.setText("Hora: ");

        jLabel11.setText("Precio: ");

        jLabel12.setText("Hora: ");

        jLabel13.setText("Precio: ");

        lblTiempoCompu1.setText("00:00:00");

        lblTiempoCompu2.setText("00:00:00");

        lblTiempoXbox1.setText("00:00:00");

        lblTiempoCompu3.setText("00:00:00");

        lblTiempoCompu4.setText("00:00:00");

        lblTiempoXbox2.setText("00:00:00");

        lblPrecioCompu1.setText("0.00");

        lblPrecioCompu2.setText("0.00");

        lblPrecioXbox1.setText("0.00");

        lblPrecioCompu3.setText("0.00");

        lblPrecioCompu4.setText("0.00");

        lblPrecioXbox2.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTiempoCompu3)
                        .addGap(39, 400, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnComputadora1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnComputadora3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnComputadora4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblPrecioCompu4)
                                                    .addComponent(lblTiempoCompu4))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnXbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblPrecioXbox2)
                                                    .addComponent(lblTiempoXbox2)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnComputadora2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Hora)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblTiempoCompu2)
                                                    .addGap(85, 85, 85)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblPrecioCompu2)
                                                .addGap(90, 90, 90)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblPrecioXbox1))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnXbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblTiempoXbox1)
                                                    .addGap(77, 77, 77)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTiempoCompu1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecioCompu1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecioCompu3)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnComputadora2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnComputadora1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Hora)
                    .addComponent(jLabel6)
                    .addComponent(lblTiempoCompu1)
                    .addComponent(lblTiempoCompu2)
                    .addComponent(lblTiempoXbox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPrecioCompu1)
                    .addComponent(lblPrecioCompu2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(lblPrecioXbox1))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComputadora3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComputadora4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(lblTiempoCompu3)
                    .addComponent(lblTiempoCompu4)
                    .addComponent(lblTiempoXbox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(lblPrecioCompu3)
                    .addComponent(lblPrecioCompu4)
                    .addComponent(lblPrecioXbox2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void btnComputadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputadora1ActionPerformed

        String tiempoSalida = JOptionPane.showInputDialog("Ingrese el tiempo");        
        this.iniciarUsoCompu(tiempoSalida, 0);
        
    }//GEN-LAST:event_btnComputadora1ActionPerformed

    private void btnComputadora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputadora2ActionPerformed
       
        String tiempoSalida = JOptionPane.showInputDialog("Ingrese el tiempo");
        this.iniciarUsoCompu(tiempoSalida, 1);
        
    }//GEN-LAST:event_btnComputadora2ActionPerformed

    private void btnComputadora3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputadora3ActionPerformed
        
        String tiempoSalida = JOptionPane.showInputDialog("Ingrese el tiempo");
        this.iniciarUsoCompu(tiempoSalida, 2);
        
    }//GEN-LAST:event_btnComputadora3ActionPerformed

    private void btnComputadora4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputadora4ActionPerformed
        
        String tiempoSalida = JOptionPane.showInputDialog("Ingrese el tiempo");
        this.iniciarUsoCompu(tiempoSalida, 3);
        
    }//GEN-LAST:event_btnComputadora4ActionPerformed

    private void btnXbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXbox1ActionPerformed
        
        String tiempoSalida = JOptionPane.showInputDialog("Ingrese el tiempo");
        this.iniciarUsoXbox(tiempoSalida,0);
        
    }//GEN-LAST:event_btnXbox1ActionPerformed

    private void btnXbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXbox2ActionPerformed
        
        String tiempoSalida = JOptionPane.showInputDialog("Ingrese el tiempo");
       this.iniciarUsoXbox(tiempoSalida,1);
        
    }//GEN-LAST:event_btnXbox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hora;
    private javax.swing.JButton btnComputadora1;
    private javax.swing.JButton btnComputadora2;
    private javax.swing.JButton btnComputadora3;
    private javax.swing.JButton btnComputadora4;
    private javax.swing.JButton btnXbox1;
    private javax.swing.JButton btnXbox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPrecioCompu1;
    private javax.swing.JLabel lblPrecioCompu2;
    private javax.swing.JLabel lblPrecioCompu3;
    private javax.swing.JLabel lblPrecioCompu4;
    private javax.swing.JLabel lblPrecioXbox1;
    private javax.swing.JLabel lblPrecioXbox2;
    private javax.swing.JLabel lblTiempoCompu1;
    private javax.swing.JLabel lblTiempoCompu2;
    private javax.swing.JLabel lblTiempoCompu3;
    private javax.swing.JLabel lblTiempoCompu4;
    private javax.swing.JLabel lblTiempoXbox1;
    private javax.swing.JLabel lblTiempoXbox2;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Me agrega un observador a un cronometro
     * @param obs La ventana MenuPrincipal
     * @param posicion La posicion de la computadora dentro del arreglo
     */
    private void agregarObservadorCompu(Observador obs, int posicion){
        ctrlAdministradores.getAdminComputadoras().
                getCompu(posicion).getCronometro().getObservado().agregar(this);                
    }
    
    private void agregarObservadorXbox(Observador obs, int posicion){
        ctrlAdministradores.getAdminXboxs().
                getXbox(posicion).getCronometro().getObservado().agregar(this);
    }
    
    private void iniciarUsoCompu(String tiempoSalida, int numCompu){
        ctrlAdministradores.iniciarComputadora(tiempoSalida, numCompu);
        int posicionCompu = ctrlAdministradores.getAdminComputadoras()
                                        .getPosicionCompuActual();
        agregarObservadorCompu(this, posicionCompu);
        
    }
    
    private void iniciarUsoXbox(String tiempoSalida,int numXbox){
        
        ctrlAdministradores.iniciarXbox(tiempoSalida, numXbox);
        int posicionXbox = ctrlAdministradores.getAdminXboxs().
                                        getPosicionActual();
        agregarObservadorXbox(this, posicionXbox);
        
    }
    
    /**
     * Actualizar los datos del observador
     * @param tiempo El tiempo que transcurre
     * @param numero El numero de maquina
     * @param maquina El tipo de maquina (RentaComputadora o RentaXbox)
     */
    @Override
    public void actualizarTiempo(String tiempo, int numero, String maquina) {

        switch (maquina) {
            
            case "Computadora":
                this.actualizarTiempoComputadora(numero, tiempo);
                break;
                
            case "Xbox":
                this.actualizarTiempoXbox(numero, tiempo);
                break;
                
            default:
                JOptionPane.showMessageDialog(this, "Error, Xbox");
                
        }
        
    }
    
    @Override
    public void actualizarPrecio(String precio, int numero, String maquina){
        
         switch (maquina) {
            
            case "Computadora":
                this.actualizarPrecioComputadora(numero, precio);
                break;
                
            case "Xbox":
                this.actualizarPrecioXbox(numero, precio);
                break;
                
            default:
                JOptionPane.showMessageDialog(this, "Error, Xbox");
                
        }
        
    }
    
    /**
     * Me actualiza el labal de una computadora
     * @param numComputadora El numero de la computadora
     * @param tiempo El tiempo que transcurre
     */
    private void actualizarTiempoComputadora(int numComputadora, String tiempo) {
        
        int numero = numComputadora;

        switch (numero) {
            
            case 0:
                lblTiempoCompu1.setText(tiempo);
                break;
                
            case 1:
                lblTiempoCompu2.setText(tiempo);
                break;
                
            case 2:
                lblTiempoCompu3.setText(tiempo);
                break;
                
            case 3:
                lblTiempoCompu4.setText(tiempo);
                break;
                
            default:
                JOptionPane.showMessageDialog(this, "Error, Computadora");
                
        }
        
    }

    /**
     * Me actualiza el labal de un RentaXbox
     * @param numXbox El numero del RentaXbox
     * @param tiempo El tiempo que transcurre
     */
    private void actualizarTiempoXbox(int numXbox, String tiempo) {
        
        int numero = numXbox;

        switch (numero) {
            case 0:
                lblTiempoXbox1.setText(tiempo);
                break;
            case 1:
                lblTiempoXbox2.setText(tiempo);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Error, Xbox");
        }
        
    }

    private void actualizarPrecioComputadora(int numComputadora, String precio) {
        
        int numero = numComputadora;

        switch (numero) {
            
            case 0:
                lblPrecioCompu1.setText(precio);
                break;
                
            case 1:
                lblPrecioCompu2.setText(precio);
                break;
                
            case 2:
                lblPrecioCompu3.setText(precio);
                break;
                
            case 3:
                lblPrecioCompu4.setText(precio);
                break;
                
            default:
                JOptionPane.showMessageDialog(this, "Error, Computadora");
                
        }
        
    }

    

    private void actualizarPrecioXbox(int numXbox, String precio) {
         
        int numero = numXbox;

        switch (numero) {
            case 0:
                lblPrecioXbox1.setText(precio);
                break;
                
            case 1:
                lblPrecioXbox2.setText(precio);
                break;
                
            default:
                JOptionPane.showMessageDialog(this, "Error, Xbox");
        }
    }
    
}
