/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtrlReportes;
import Modelo.GananciaPorServicio;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author hyuchiha
 */
public class ReporteHecho extends javax.swing.JFrame {
    
    CtrlReportes reportes;
    Date fechaInicio;
    Date fechaFinal;
    
    ArrayList<GananciaPorServicio> compusId;
    ArrayList<GananciaPorServicio> xboxId;
    ArrayList<GananciaPorServicio> productoId;
    
    /**
     * Creates new form ReporteHecho
     */
    public ReporteHecho() {
        initComponents();
        reportes = new CtrlReportes();
        GenerarElReporte();
        
    }
    
    public void setfechaInicio(Date fecha){
        this.fechaInicio = fecha;
    }
    
    public void serfechaFinal(Date fecha){
        this.fechaFinal = fecha;
    }
    
    public void GenerarElReporte(){
        double gananciaCompus = reportes.obtenerGananciaComputadoras(fechaInicio, fechaFinal);
        double gananciaxbox = reportes.obtenerGananciarXboxs(fechaInicio, fechaFinal);
        double gananciaProductos = reportes.obtenerGananciaProductos(fechaInicio, fechaFinal);
        
        this.compusId = reportes.obtenerGananciaPorCadaComputadora(fechaInicio, fechaFinal);
        this.xboxId = reportes.obtenerGananciaPorCadaXbox(fechaInicio, fechaFinal);
        this.productoId = reportes.obtenerGananciaPorCadaProducto(fechaInicio, fechaFinal);
        
        this.textGanCompu.setText(Double.toString(gananciaCompus));
        this.txtGanxbox.setText(Double.toString(gananciaxbox));
        this.tetxganprod.setText(Double.toString(gananciaProductos));
        this.texttotal.setText(Double.toString(gananciaCompus +  gananciaxbox+ gananciaProductos));
        
        setValuesForIDCompu();
        setValuesForIDxbox();
        setValuesForIDproducto();
    }
    
    public void setValuesForIDCompu(){
        DefaultComboBoxModel modeloCombo= new DefaultComboBoxModel();
        
        for(GananciaPorServicio servicio :compusId){
            modeloCombo.addElement(servicio.getProducto());
        }
        
        this.ComboComputadora.setModel(modeloCombo);
    }
    
    public void setValuesForIDxbox(){
        DefaultComboBoxModel modeloCombo= new DefaultComboBoxModel();
        
        for(GananciaPorServicio servicio :compusId){
            modeloCombo.addElement(servicio.getProducto());
        }
        
        this.ComboComputadora.setModel(modeloCombo);
    }
    
    public void setValuesForIDproducto(){
        DefaultComboBoxModel modeloCombo= new DefaultComboBoxModel();
        
        for(GananciaPorServicio servicio :compusId){
            modeloCombo.addElement(servicio.getProducto());
        }
        
        this.ComboComputadora.setModel(modeloCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textGanCompu = new javax.swing.JTextField();
        txtGanxbox = new javax.swing.JTextField();
        tetxganprod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ComboComputadora = new javax.swing.JComboBox();
        textIdcomp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboXbox = new javax.swing.JComboBox();
        textidxbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboProducto = new javax.swing.JComboBox();
        textidprod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        texttotal = new javax.swing.JTextField();
        buttonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ganancia de las computadoras:");

        jLabel2.setText("Ganancia de los Xbox:");

        jLabel3.setText("Ganancia de lso productos:");

        textGanCompu.setEditable(false);

        txtGanxbox.setEditable(false);

        tetxganprod.setEditable(false);

        jLabel4.setText("Ganancia Por cada Computadora:");

        ComboComputadora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboComputadora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboComputadoraItemStateChanged(evt);
            }
        });

        textIdcomp.setEditable(false);

        jLabel5.setText("Ganancia por cada xbox");

        comboXbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboXbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboXboxItemStateChanged(evt);
            }
        });

        textidxbox.setEditable(false);

        jLabel6.setText("Ganancia por cada producto:");

        comboProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProductoItemStateChanged(evt);
            }
        });

        textidprod.setEditable(false);

        jLabel7.setText("Ganancias totales:");

        texttotal.setEditable(false);

        buttonAceptar.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(37, 37, 37)
                            .addComponent(textGanCompu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGanxbox, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(tetxganprod))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboXbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ComboComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textidprod, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(textidxbox)
                                    .addComponent(textIdcomp)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(buttonAceptar)
                                        .addGap(10, 10, 10)))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textGanCompu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGanxbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tetxganprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIdcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboXbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textidxbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textidprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(texttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(buttonAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboComputadoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboComputadoraItemStateChanged
        // TODO add your handling code here:
        this.textIdcomp.setText((String)this.ComboComputadora.getSelectedItem());
    }//GEN-LAST:event_ComboComputadoraItemStateChanged

    private void comboXboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboXboxItemStateChanged
        // TODO add your handling code here:
        this.textidxbox.setText((String)this.comboProducto.getSelectedItem());
    }//GEN-LAST:event_comboXboxItemStateChanged

    private void comboProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProductoItemStateChanged
        // TODO add your handling code here:
        this.textidprod.setText((String)this.comboProducto.getSelectedItem());
    }//GEN-LAST:event_comboProductoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteHecho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteHecho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteHecho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteHecho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteHecho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboComputadora;
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JComboBox comboProducto;
    private javax.swing.JComboBox comboXbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tetxganprod;
    private javax.swing.JTextField textGanCompu;
    private javax.swing.JTextField textIdcomp;
    private javax.swing.JTextField textidprod;
    private javax.swing.JTextField textidxbox;
    private javax.swing.JTextField texttotal;
    private javax.swing.JTextField txtGanxbox;
    // End of variables declaration//GEN-END:variables
}
